[tox]
envlist =
    clean
    lint
    py31{2-4}
    htmlcov
skip_missing_interpreters = true

[tool:pytest]
testpaths =
    tests
addopts = 
    --cov-report=term-missing

[gh]
python =
    3.12 = py312
    3.13 = py313
    3.14 = py314, htmlcov

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
# extras =
commands =
    coverage run --parallel-mode -m pytest --ignore=tests/data --ignore=Scripts {posargs}

[testenv:lint]
description: Check import order and code formatting
runner = uv-venv-lock-runner
skip_install = true
commands =
    ruff check --select I  # Check import order
    ruff format --check --diff  # Check formatting
    flake8 src

[testenv:htmlcov]
description: Report coverage over all test runs
skip_install = true
commands =
    coverage combine
    coverage report
    coverage html

[testenv:clean]
skip_install = true
commands =
    coverage erase
